# .chartreleaser.yaml is the configuration file for chart-releaser, a CI tool
# to update Helm Charts on application release. See the documentation at
# https://github.com/edaniszewski/chart-releaser

version: v1
chart:
  name: synse-loadgen
  path: synse-loadgen
  repo: github.com/vapor-ware/synse-charts
commit:
  author:
    name: vio-bot
    email: 'marco+viogh@vapor.io'
extras:
- path: synse-loadgen/README.md
  updates:
  - search: '\| `image\.tag` \| The tag of the image to use\. \| `[0-9a-zA-Z.-]*` \|'
    replace: '| `image.tag` | The tag of the image to use. | `{{ .App.NewVersion }}` |'
- path: synse-loadgen/values.yaml
  updates:
  - search: 'tag: "[0-9a-zA-Z.-]*"'
    replace: 'tag: "{{ .App.NewVersion }}"'
